#!/usr/bin/env python3
"""生成 LCD 中文字库数据 (16x16 点阵) — 输出 lcd_font_cn_data.h"""

import os
import sys

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("ERROR: Pillow not installed. Run: pip install Pillow", file=sys.stderr)
    sys.exit(1)

# ============================================================
# 所有需要显示的汉字（去重后按 Unicode 排序）
# ============================================================
CHARS = (
    "斗地主计分"          # 标题
    "状态总"              # 标签：状态/总分
    "语音指令"            # 标签：语音指令
    "初始化中"            # 状态：初始化中...
    "就绪你好小鑫"        # 状态：就绪 你好小鑫
    "已更新"              # 状态：计分已更新
    "查询"                # 状态：查询中...
    "重置完成"            # 状态：重置完成 / 日志重置标记
    "全部清空"            # 状态：全部已清空
    "撤销"                # 状态：已撤销
    "我在听"              # 状态：我在听...
    "日志"                # 日志标题：计分日志
    "局玩"                # 日志列头：局/玩/地/分
    "短按翻页"            # 日志提示：短按翻页
    "长退出秒"            # 日志提示：长按退出 30秒
    "无记录"              # 日志空：无记录
)

# 去重并按 Unicode 码点升序排列（便于二分查找）
unique_chars = sorted(set(CHARS))
print(f"Total unique Chinese chars: {len(unique_chars)}")

# ============================================================
# 查找系统字体
# ============================================================
FONT_CANDIDATES = [
    "C:/Windows/Fonts/simhei.ttf",    # 黑体 — 小字号下清晰
    "C:/Windows/Fonts/msyh.ttc",      # 微软雅黑
    "C:/Windows/Fonts/simsun.ttc",    # 宋体
    "C:/Windows/Fonts/DENG.TTF",      # 等线
]

font_path = None
for p in FONT_CANDIDATES:
    if os.path.exists(p):
        font_path = p
        break

if not font_path:
    print("ERROR: No Chinese font found in C:/Windows/Fonts/", file=sys.stderr)
    sys.exit(1)

print(f"Using font: {font_path}")

# ============================================================
# 渲染参数
# ============================================================
GLYPH_W = 16
GLYPH_H = 16
FONT_SIZE = 15        # 略小于 16，留出边距避免笔画贴边
THRESHOLD = 120       # 灰度阈值：> 此值视为前景


def render_char(ch):
    """渲染单个汉字到 16x16 点阵，返回 32 字节 list（2 bytes/row x 16 rows）。"""
    img = Image.new('L', (GLYPH_W, GLYPH_H), 0)   # 灰度黑底
    draw = ImageDraw.Draw(img)
    font = ImageFont.truetype(font_path, FONT_SIZE)

    # 获取文字边界框并居中
    bbox = draw.textbbox((0, 0), ch, font=font)
    w = bbox[2] - bbox[0]
    h = bbox[3] - bbox[1]
    x = (GLYPH_W - w) // 2 - bbox[0]
    y = (GLYPH_H - h) // 2 - bbox[1]
    draw.text((x, y), ch, fill=255, font=font)

    # 阈值化并提取点阵：每行 2 字节，MSB = 最左像素
    bitmap = []
    pixels = img.load()
    for row in range(GLYPH_H):
        b0 = 0   # 左 8 像素
        b1 = 0   # 右 8 像素
        for col in range(8):
            if pixels[col, row] > THRESHOLD:
                b0 |= (0x80 >> col)
        for col in range(8):
            if pixels[col + 8, row] > THRESHOLD:
                b1 |= (0x80 >> col)
        bitmap.append(b0)
        bitmap.append(b1)

    return bitmap


# ============================================================
# 渲染所有汉字
# ============================================================
char_data = []
for ch in unique_chars:
    cp = ord(ch)
    bmp = render_char(ch)
    char_data.append((cp, ch, bmp))
    # 预览点阵
    preview = ""
    for row in range(GLYPH_H):
        line = ""
        for col in range(GLYPH_W):
            byte_idx = col // 8
            bit_idx = col % 8
            on = (bmp[row * 2 + byte_idx] >> (7 - bit_idx)) & 1
            line += "█" if on else "·"
        preview += f"  {line}\n"
    print(f"U+{cp:04X} {ch}:\n{preview}")

# ============================================================
# 生成 C 头文件
# ============================================================
output_path = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "src", "lcd_font_cn_data.h"
)

with open(output_path, "w", encoding="utf-8") as f:
    f.write("/* Auto-generated by gen_chinese_font.py - DO NOT EDIT */\n")
    f.write(f"/* {len(char_data)} Chinese glyphs, 16x16, sorted by Unicode */\n")
    f.write("#pragma once\n\n")
    f.write("#include <stdint.h>\n\n")

    # 码点表（升序，便于二分查找）
    f.write("/* Unicode codepoints, sorted ascending for binary search */\n")
    f.write(f"static const uint16_t cn_codepoints[{len(char_data)}] = {{\n")
    for cp, ch, _ in char_data:
        f.write(f"    0x{cp:04X},  /* {ch} */\n")
    f.write("};\n\n")

    # 位图表
    f.write("/* Glyph bitmaps: each 32 bytes (16 rows x 2 bytes/row), MSB=left */\n")
    f.write(f"static const uint8_t cn_bitmaps[{len(char_data)}][32] = {{\n")
    for cp, ch, bmp in char_data:
        hex_str = ",".join(f"0x{b:02X}" for b in bmp)
        f.write(f"    {{{hex_str}}},  /* U+{cp:04X} {ch} */\n")
    f.write("};\n\n")

    f.write(f"#define CN_FONT_COUNT {len(char_data)}\n")

print(f"\nGenerated: {output_path}")
print(f"Data size: {len(char_data) * 32} bytes ({len(char_data) * 32 / 1024:.1f} KB)")
